/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testubes;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Hafiz
 */
public class DataAnak extends javax.swing.JInternalFrame {

    /**
     * Creates new form DataAS
     */
    public DataAnak() {
        initComponents();
        tampilkan_data();
       
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        
    }
    
    EditDataAnak show = new EditDataAnak();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        layarutama = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_anak_asuh = new javax.swing.JTable();
        tmblEdit = new javax.swing.JButton();
        tmblHapus = new javax.swing.JButton();
        tmblInput = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1040, 782));
        setVisible(false);

        layarutama.setBackground(new java.awt.Color(0, 204, 204));
        layarutama.setPreferredSize(new java.awt.Dimension(1040, 748));

        tabel_anak_asuh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nama", "Tanggal Masuk", "Tanggal Lahir", "Penyakit", "Keterangan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel_anak_asuh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_anak_asuhMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_anak_asuh);
        if (tabel_anak_asuh.getColumnModel().getColumnCount() > 0) {
            tabel_anak_asuh.getColumnModel().getColumn(0).setResizable(false);
            tabel_anak_asuh.getColumnModel().getColumn(1).setResizable(false);
            tabel_anak_asuh.getColumnModel().getColumn(2).setResizable(false);
            tabel_anak_asuh.getColumnModel().getColumn(3).setResizable(false);
            tabel_anak_asuh.getColumnModel().getColumn(4).setResizable(false);
        }

        tmblEdit.setText("Edit");
        tmblEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmblEditActionPerformed(evt);
            }
        });

        tmblHapus.setText("Delete");
        tmblHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmblHapusActionPerformed(evt);
            }
        });

        tmblInput.setText("Input");
        tmblInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmblInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layarutamaLayout = new javax.swing.GroupLayout(layarutama);
        layarutama.setLayout(layarutamaLayout);
        layarutamaLayout.setHorizontalGroup(
            layarutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layarutamaLayout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addGroup(layarutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layarutamaLayout.createSequentialGroup()
                        .addComponent(tmblInput)
                        .addGap(18, 18, 18)
                        .addComponent(tmblHapus)
                        .addGap(18, 18, 18)
                        .addComponent(tmblEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(205, 205, 205))
        );
        layarutamaLayout.setVerticalGroup(
            layarutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layarutamaLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layarutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tmblEdit)
                    .addComponent(tmblHapus)
                    .addComponent(tmblInput))
                .addGap(349, 349, 349))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(layarutama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(layarutama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tmblEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmblEditActionPerformed
        // TODO add your handling code here:
        ListSelectionModel select = tabel_anak_asuh.getSelectionModel();
        if(! select.isSelectionEmpty()){
                int index = tabel_anak_asuh.getSelectedRow();
                TableModel  model= tabel_anak_asuh.getModel();
                String nama=model.getValueAt(index, 0).toString();
                String tglmasuk=model.getValueAt(index, 1).toString();
                String tgllahir=model.getValueAt(index, 2).toString();
                String penyakit=model.getValueAt(index, 3).toString();
                String ket=model.getValueAt(index, 4).toString();
                
                layarutama.removeAll();
                
                layarutama.add(show).setVisible(true);
                show.pack();
                //show.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                
                show.nama.setText(nama);
                show.tanggalmasuk.setText(tglmasuk);
                show.tanggallahir.setText(tgllahir);
                show.penyakit.setText(penyakit);
                show.keterangan.setText(ket);
            }
            else{
                JOptionPane.showMessageDialog(null,"PILIH DATA YANG INGIN DIEDIT !!!","PEMBERITAHUAN",JOptionPane.INFORMATION_MESSAGE);
            }
    }//GEN-LAST:event_tmblEditActionPerformed

    private void tmblInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmblInputActionPerformed
        // TODO add your handling code here:
        layarutama.removeAll();
        TambahDataAnak tda=new TambahDataAnak();
        layarutama.add(tda).setVisible(true);
    }//GEN-LAST:event_tmblInputActionPerformed

    private void tmblHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmblHapusActionPerformed
        // TODO add your handling code here:
        try{
            int baris= tabel_anak_asuh.getSelectedRow();
            String nama=tabel_anak_asuh.getModel().getValueAt(baris,0).toString();
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/panti_asuhan","root","");
            Statement stat=conn.createStatement();
            String sql="DELETE FROM `tabel_anak_asuh` WHERE nama='"+nama+"'";
            if(stat.executeUpdate(sql)==1){
                JOptionPane.showMessageDialog(null,"ANDA BERHASIL MENGHAPUS DATA","PEMBERITAHUAN",JOptionPane.INFORMATION_MESSAGE);
                
                //new data_pegawai().setVisible(true);
                //this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(null,"MAAF DATA TIDAK BISA DI HAPUS","PEMBERITAHUAN",JOptionPane.INFORMATION_MESSAGE);
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        layarutama.removeAll();
        DataAnak tda=new DataAnak();
        layarutama.add(tda).setVisible(true);
    }//GEN-LAST:event_tmblHapusActionPerformed

    private void tabel_anak_asuhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_anak_asuhMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tabel_anak_asuhMouseClicked

    private void tampilkan_data(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Nama");
        model.addColumn("Tanggal Masuk");
        model.addColumn("Tanggal Lahir");
        model.addColumn("Penyakit");
        model.addColumn("Keterangan");
        try{
            int no=1;
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/panti_asuhan","root","");
            Statement stat=conn.createStatement();
            String sql = "SELECT * FROM `tabel_anak_asuh`";
            ResultSet rs = stat.executeQuery(sql);
            while(rs.next()){
                model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5)});
                no++;
            }
            tabel_anak_asuh.setModel(model);
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
            //System.out.println("Error : "+ e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel layarutama;
    public static javax.swing.JTable tabel_anak_asuh;
    private javax.swing.JButton tmblEdit;
    private javax.swing.JButton tmblHapus;
    private javax.swing.JButton tmblInput;
    // End of variables declaration//GEN-END:variables
}
