/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testubes;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author User
 */
public class DataInventaris extends javax.swing.JInternalFrame {

    /**
     * Creates new form dataInventaris
     */
    public DataInventaris() {
        initComponents();
        tampilkan_data();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        
    }
    EditInventaris show= new EditInventaris();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layarutama = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_data_inventaris = new javax.swing.JTable();
        tmblHapus = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        tmblInput = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1040, 782));

        layarutama.setBackground(new java.awt.Color(0, 204, 204));
        layarutama.setPreferredSize(new java.awt.Dimension(1040, 782));

        tabel_data_inventaris.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama", "Jenis", "Jumlah", "Donatur"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabel_data_inventaris);
        if (tabel_data_inventaris.getColumnModel().getColumnCount() > 0) {
            tabel_data_inventaris.getColumnModel().getColumn(0).setResizable(false);
            tabel_data_inventaris.getColumnModel().getColumn(1).setResizable(false);
            tabel_data_inventaris.getColumnModel().getColumn(2).setResizable(false);
            tabel_data_inventaris.getColumnModel().getColumn(3).setResizable(false);
        }

        tmblHapus.setText("Delete");
        tmblHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmblHapusActionPerformed(evt);
            }
        });

        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        tmblInput.setText("Input");
        tmblInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmblInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layarutamaLayout = new javax.swing.GroupLayout(layarutama);
        layarutama.setLayout(layarutamaLayout);
        layarutamaLayout.setHorizontalGroup(
            layarutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layarutamaLayout.createSequentialGroup()
                .addGroup(layarutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layarutamaLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layarutamaLayout.createSequentialGroup()
                        .addGap(599, 599, 599)
                        .addComponent(tmblInput)
                        .addGap(18, 18, 18)
                        .addComponent(tmblHapus)
                        .addGap(18, 18, 18)
                        .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(221, Short.MAX_VALUE))
        );
        layarutamaLayout.setVerticalGroup(
            layarutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layarutamaLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layarutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edit)
                    .addComponent(tmblHapus)
                    .addComponent(tmblInput))
                .addContainerGap(357, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layarutama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layarutama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        ListSelectionModel select = tabel_data_inventaris.getSelectionModel();
        if(! select.isSelectionEmpty()){
                int index = tabel_data_inventaris.getSelectedRow();
                TableModel  model= tabel_data_inventaris.getModel();
                String nama=model.getValueAt(index, 0).toString();
                String jenis=model.getValueAt(index, 1).toString();
                String jumlah=model.getValueAt(index, 2).toString();
                String donatur=model.getValueAt(index, 3).toString();
                
                layarutama.removeAll();
                
                layarutama.add(show).setVisible(true);
                show.pack();
                //show.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                
                show.nama.setText(nama);
                show.jenis.setText(jenis);
                show.jumlah.setText(jumlah);
                show.donatur.setText(donatur);
                
            }
            else{
                JOptionPane.showMessageDialog(null,"PILIH DATA YANG INGIN DIEDIT !!!","PEMBERITAHUAN",JOptionPane.INFORMATION_MESSAGE);
            }
    }//GEN-LAST:event_editActionPerformed

    private void tmblInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmblInputActionPerformed
        // TODO add your handling code here:
        layarutama.removeAll();
        TambahInventaris ti = new TambahInventaris();
        layarutama.add(ti).setVisible(true);
    }//GEN-LAST:event_tmblInputActionPerformed

    private void tmblHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmblHapusActionPerformed
        // TODO add your handling code here:
        try{
            int baris= tabel_data_inventaris.getSelectedRow();
            String nama=tabel_data_inventaris.getModel().getValueAt(baris,0).toString();
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/panti_asuhan","root","");
            Statement stat=conn.createStatement();
            String sql="DELETE FROM `tabel_inventaris` WHERE nama='"+nama+"'";
            if(stat.executeUpdate(sql)>=1){
                JOptionPane.showMessageDialog(null,"ANDA BERHASIL MENGHAPUS DATA","PEMBERITAHUAN",JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(null,"MAAF DATA TIDAK BISA DI HAPUS","PEMBERITAHUAN",JOptionPane.INFORMATION_MESSAGE);
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
            //System.out.println("Error : "+ e.getMessage());
        }
        layarutama.removeAll();
        DataInventaris di=new DataInventaris();
        layarutama.add(di).setVisible(true);
    }//GEN-LAST:event_tmblHapusActionPerformed

    private void tampilkan_data(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Nama");
        model.addColumn("Jenis");
        model.addColumn("Jumlah");
        model.addColumn("Donatur");
        try{
            int no=1;
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/panti_asuhan","root","");
            Statement stat=conn.createStatement();
            String sql = "SELECT * FROM `tabel_inventaris`";
            ResultSet rs = stat.executeQuery(sql);
            while(rs.next()){
                model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4)});
                no++;
            }
            tabel_data_inventaris.setModel(model);
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
            //System.out.println("Error : "+ e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton edit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel layarutama;
    public static javax.swing.JTable tabel_data_inventaris;
    private javax.swing.JButton tmblHapus;
    private javax.swing.JButton tmblInput;
    // End of variables declaration//GEN-END:variables
}
