/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testubes;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Hafiz
 */
public class DataPegawai extends javax.swing.JInternalFrame {

    /**
     * Creates new form Datapegawai
     */
    public DataPegawai() {
        initComponents();
        tampilkan_data();
         this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
    }
    EditPegawai show=new EditPegawai();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        layarutama = new javax.swing.JPanel();
        tmblEdit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_data_pegawai = new javax.swing.JTable();
        tmblHapus = new javax.swing.JButton();
        tmblTambah = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setPreferredSize(new java.awt.Dimension(1040, 782));

        layarutama.setBackground(new java.awt.Color(0, 204, 204));
        layarutama.setPreferredSize(new java.awt.Dimension(1040, 782));

        tmblEdit.setText("Edit");
        tmblEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmblEditActionPerformed(evt);
            }
        });

        tabel_data_pegawai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nama", "NIP", "Jabatan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel_data_pegawai.setMinimumSize(new java.awt.Dimension(75, 64));
        tabel_data_pegawai.setPreferredSize(new java.awt.Dimension(375, 64));
        jScrollPane1.setViewportView(tabel_data_pegawai);
        if (tabel_data_pegawai.getColumnModel().getColumnCount() > 0) {
            tabel_data_pegawai.getColumnModel().getColumn(0).setResizable(false);
            tabel_data_pegawai.getColumnModel().getColumn(1).setResizable(false);
            tabel_data_pegawai.getColumnModel().getColumn(2).setResizable(false);
        }

        tmblHapus.setText("Delete");
        tmblHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmblHapusActionPerformed(evt);
            }
        });

        tmblTambah.setText("Input");
        tmblTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmblTambahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layarutamaLayout = new javax.swing.GroupLayout(layarutama);
        layarutama.setLayout(layarutamaLayout);
        layarutamaLayout.setHorizontalGroup(
            layarutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layarutamaLayout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addGroup(layarutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layarutamaLayout.createSequentialGroup()
                        .addComponent(tmblTambah)
                        .addGap(18, 18, 18)
                        .addComponent(tmblHapus)
                        .addGap(18, 18, 18)
                        .addComponent(tmblEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(221, Short.MAX_VALUE))
        );
        layarutamaLayout.setVerticalGroup(
            layarutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layarutamaLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layarutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tmblEdit)
                    .addComponent(tmblHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tmblTambah))
                .addContainerGap(357, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layarutama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layarutama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tmblEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmblEditActionPerformed
        // TODO add your handling code here:
        ListSelectionModel select = tabel_data_pegawai.getSelectionModel();
        if(! select.isSelectionEmpty()){
                int index = tabel_data_pegawai.getSelectedRow();
                TableModel  model= tabel_data_pegawai.getModel();
                String nama=model.getValueAt(index, 0).toString();
                String nip=model.getValueAt(index, 1).toString();
                String jabatan=model.getValueAt(index, 2).toString();
                
                layarutama.removeAll();
                
                layarutama.add(show).setVisible(true);
                show.pack();
                //show.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                
                show.nama.setText(nama);
                show.nip.setText(nip);
                show.jabatan.setText(jabatan);
                
            }
            else{
                JOptionPane.showMessageDialog(null,"PILIH DATA YANG INGIN DIEDIT !!!","PEMBERITAHUAN",JOptionPane.INFORMATION_MESSAGE);
            }
    }//GEN-LAST:event_tmblEditActionPerformed

    private void tmblTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmblTambahActionPerformed
        // TODO add your handling code here:
        layarutama.removeAll();
        TambahPegawai tp = new TambahPegawai();
        layarutama.add(tp).setVisible(true);
    }//GEN-LAST:event_tmblTambahActionPerformed

    private void tmblHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmblHapusActionPerformed
        // TODO add your handling code here:
        try{
            int baris= tabel_data_pegawai.getSelectedRow();
            String nama=tabel_data_pegawai.getModel().getValueAt(baris,0).toString();
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/panti_asuhan","root","");
            Statement stat=conn.createStatement();
            String sql="DELETE FROM `tabel_pegawai` WHERE nama='"+nama+"'";
            if(stat.executeUpdate(sql)>=1){
                JOptionPane.showMessageDialog(null,"ANDA BERHASIL MENGHAPUS DATA","PEMBERITAHUAN",JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(null,"MAAF DATA TIDAK BISA DI HAPUS","PEMBERITAHUAN",JOptionPane.INFORMATION_MESSAGE);
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
            //System.out.println("Error : "+ e.getMessage());
        }
        layarutama.removeAll();
        DataPegawai dp=new DataPegawai();
        layarutama.add(dp).setVisible(true);
    }//GEN-LAST:event_tmblHapusActionPerformed

    private void tampilkan_data(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Nama");
        model.addColumn("NIP");
        model.addColumn("Jabatan");
        try{
            int no=1;
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/panti_asuhan","root","");
            Statement stat=conn.createStatement();
            String sql = "SELECT * FROM `tabel_pegawai`";
            ResultSet rs = stat.executeQuery(sql);
            while(rs.next()){
                model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3)});
                no++;
            }
            tabel_data_pegawai.setModel(model);
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
            //System.out.println("Error : "+ e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    public static javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel layarutama;
    public static javax.swing.JTable tabel_data_pegawai;
    private javax.swing.JButton tmblEdit;
    private javax.swing.JButton tmblHapus;
    private javax.swing.JButton tmblTambah;
    // End of variables declaration//GEN-END:variables
}
