/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testubes;

import javafx.scene.paint.Color;
import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author Hafiz
 */
public class menu_utama extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public menu_utama() {
        initComponents();
        this.setLocationRelativeTo(this);
        Gambar ma = new Gambar();
        layarUtama.add(ma).setVisible(true);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        DataPengurus1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        DataAnak = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        DataPegawai = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        DataInventaris = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        DataPengurusPanti = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        DataPengurus = new javax.swing.JLabel();
        Admin = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        DataPengurus3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        layarUtama = new javax.swing.JPanel();

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Home2.png"))); // NOI18N

        DataPengurus1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        DataPengurus1.setForeground(new java.awt.Color(255, 255, 255));
        DataPengurus1.setText("Data Pengurus Panti");

        setTitle("APLIKASI PENDATAAN PANTI ASUHAN");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        jPanel6.setBackground(new java.awt.Color(0, 153, 153));

        DataAnak.setBackground(new java.awt.Color(0, 153, 153));
        DataAnak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DataAnakMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DataAnakMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DataAnakMouseExited(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Kids.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Data Anak Asuh");

        javax.swing.GroupLayout DataAnakLayout = new javax.swing.GroupLayout(DataAnak);
        DataAnak.setLayout(DataAnakLayout);
        DataAnakLayout.setHorizontalGroup(
            DataAnakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataAnakLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DataAnakLayout.setVerticalGroup(
            DataAnakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(DataAnakLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        DataPegawai.setBackground(new java.awt.Color(0, 153, 153));
        DataPegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DataPegawaiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DataPegawaiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DataPegawaiMouseExited(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Employee2.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Data Pegawai");

        javax.swing.GroupLayout DataPegawaiLayout = new javax.swing.GroupLayout(DataPegawai);
        DataPegawai.setLayout(DataPegawaiLayout);
        DataPegawaiLayout.setHorizontalGroup(
            DataPegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataPegawaiLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addGap(35, 35, 35)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DataPegawaiLayout.setVerticalGroup(
            DataPegawaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
            .addGroup(DataPegawaiLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        DataInventaris.setBackground(new java.awt.Color(0, 153, 153));
        DataInventaris.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DataInventarisMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DataInventarisMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DataInventarisMouseExited(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Warehouse 2.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Data Inventaris");

        javax.swing.GroupLayout DataInventarisLayout = new javax.swing.GroupLayout(DataInventaris);
        DataInventaris.setLayout(DataInventarisLayout);
        DataInventarisLayout.setHorizontalGroup(
            DataInventarisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataInventarisLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel5)
                .addGap(40, 40, 40)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DataInventarisLayout.setVerticalGroup(
            DataInventarisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(DataInventarisLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel10)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        DataPengurusPanti.setBackground(new java.awt.Color(0, 153, 153));
        DataPengurusPanti.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DataPengurusPantiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DataPengurusPantiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DataPengurusPantiMouseExited(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Home2.png"))); // NOI18N

        DataPengurus.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        DataPengurus.setForeground(new java.awt.Color(255, 255, 255));
        DataPengurus.setText("Data Pengurus Panti");

        javax.swing.GroupLayout DataPengurusPantiLayout = new javax.swing.GroupLayout(DataPengurusPanti);
        DataPengurusPanti.setLayout(DataPengurusPantiLayout);
        DataPengurusPantiLayout.setHorizontalGroup(
            DataPengurusPantiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataPengurusPantiLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel7)
                .addGap(38, 38, 38)
                .addComponent(DataPengurus, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DataPengurusPantiLayout.setVerticalGroup(
            DataPengurusPantiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(DataPengurusPantiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DataPengurus, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addContainerGap())
        );

        Admin.setBackground(new java.awt.Color(0, 153, 153));
        Admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AdminMouseExited(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Setting.png"))); // NOI18N

        DataPengurus3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        DataPengurus3.setForeground(new java.awt.Color(255, 255, 255));
        DataPengurus3.setText("Admin");

        javax.swing.GroupLayout AdminLayout = new javax.swing.GroupLayout(Admin);
        Admin.setLayout(AdminLayout);
        AdminLayout.setHorizontalGroup(
            AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel8)
                .addGap(39, 39, 39)
                .addComponent(DataPengurus3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AdminLayout.setVerticalGroup(
            AdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(AdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DataPengurus3, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/bac.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Panti Asuhan Sejahtera");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DataAnak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(DataPegawai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(DataInventaris, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(DataPengurusPanti, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(DataAnak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(DataPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(DataInventaris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(DataPengurusPanti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(Admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layarUtama.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layarUtamaLayout = new javax.swing.GroupLayout(layarUtama);
        layarUtama.setLayout(layarUtamaLayout);
        layarUtamaLayout.setHorizontalGroup(
            layarUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1057, Short.MAX_VALUE)
        );
        layarUtamaLayout.setVerticalGroup(
            layarUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(layarUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(layarUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminMouseExited
        // TODO add your handling code here:
        Admin.setBackground(new java.awt.Color(0,153,153));
    }//GEN-LAST:event_AdminMouseExited

    private void AdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminMouseEntered
        // TODO add your handling code here:
        Admin.setBackground(new java.awt.Color(0,204,204));
    }//GEN-LAST:event_AdminMouseEntered

    private void AdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminMouseClicked
        // TODO add your handling code here:
        layarUtama.removeAll();
        DataAdmin ma = new DataAdmin();
        layarUtama.add(ma).setVisible(true);
        
    }//GEN-LAST:event_AdminMouseClicked

    private void DataPengurusPantiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DataPengurusPantiMouseExited
        // TODO add your handling code here:
        DataPengurusPanti.setBackground(new java.awt.Color(0,153,153));
    }//GEN-LAST:event_DataPengurusPantiMouseExited

    private void DataPengurusPantiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DataPengurusPantiMouseEntered
        // TODO add your handling code here:
        DataPengurusPanti.setBackground(new java.awt.Color(0,204,204));
    }//GEN-LAST:event_DataPengurusPantiMouseEntered

    private void DataPengurusPantiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DataPengurusPantiMouseClicked
        // TODO add your handling code here:
        layarUtama.removeAll();
        DataPengurus ma = new DataPengurus();
        layarUtama.add(ma).setVisible(true);
        
    }//GEN-LAST:event_DataPengurusPantiMouseClicked

    private void DataInventarisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DataInventarisMouseExited
        // TODO add your handling code here:
        DataInventaris.setBackground(new java.awt.Color(0,153,153));
    }//GEN-LAST:event_DataInventarisMouseExited

    private void DataInventarisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DataInventarisMouseEntered
        // TODO add your handling code here:
        DataInventaris.setBackground(new java.awt.Color(0,204,204));
    }//GEN-LAST:event_DataInventarisMouseEntered

    private void DataInventarisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DataInventarisMouseClicked
        // TODO add your handling code here:
        layarUtama.removeAll();
        DataInventaris ma = new DataInventaris();
        layarUtama.add(ma).setVisible(true);
    }//GEN-LAST:event_DataInventarisMouseClicked

    private void DataPegawaiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DataPegawaiMouseExited
        // TODO add your handling code here:
        DataPegawai.setBackground(new java.awt.Color(0,153,153));
    }//GEN-LAST:event_DataPegawaiMouseExited

    private void DataPegawaiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DataPegawaiMouseEntered
        // TODO add your handling code here:
        DataPegawai.setBackground(new java.awt.Color(0,204,204));
    }//GEN-LAST:event_DataPegawaiMouseEntered

    private void DataPegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DataPegawaiMouseClicked
        // TODO add your handling code here:
        layarUtama.removeAll();
        DataPegawai ma = new DataPegawai();
        layarUtama.add(ma).setVisible(true);
    }//GEN-LAST:event_DataPegawaiMouseClicked

    private void DataAnakMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DataAnakMouseExited
        // TODO add your handling code here:
        DataAnak.setBackground(new java.awt.Color(0,153,153));
    }//GEN-LAST:event_DataAnakMouseExited

    private void DataAnakMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DataAnakMouseEntered
        // TODO add your handling code here:
        DataAnak.setBackground(new java.awt.Color(0,204,204));
    }//GEN-LAST:event_DataAnakMouseEntered

    private void DataAnakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DataAnakMouseClicked
        // TODO add your handling code here:
        layarUtama.removeAll();
        DataAnak ma = new DataAnak();
        layarUtama.add(ma).setVisible(true);
    }//GEN-LAST:event_DataAnakMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        
       layarUtama.removeAll();
       Gambar ma = new Gambar();
       layarUtama.add(ma).setVisible(true);
        
    }//GEN-LAST:event_jLabel6MouseClicked
   
    
        
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Admin;
    private javax.swing.JPanel DataAnak;
    private javax.swing.JPanel DataInventaris;
    private javax.swing.JPanel DataPegawai;
    private javax.swing.JLabel DataPengurus;
    private javax.swing.JLabel DataPengurus1;
    private javax.swing.JLabel DataPengurus3;
    private javax.swing.JPanel DataPengurusPanti;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel layarUtama;
    // End of variables declaration//GEN-END:variables
}
