/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testubes;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author User
 */
public class TambahInventaris extends javax.swing.JInternalFrame {

    private void kosongkan_form(){
        
        nama.setText(null);
        jenis.setText(null);
        jumlah.setText(null);
        donatur.setText(null);
        
    }
    /**
     * Creates new form EditInventaris
     */
    public TambahInventaris() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layarutama = new javax.swing.JPanel();
        nama = new javax.swing.JTextField();
        jenis = new javax.swing.JTextField();
        jumlah = new javax.swing.JTextField();
        donatur = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tmblInput = new javax.swing.JButton();
        tmblKembali = new javax.swing.JButton();

        layarutama.setBackground(new java.awt.Color(0, 204, 204));
        layarutama.setPreferredSize(new java.awt.Dimension(1024, 740));

        jLabel1.setText("Nama");

        jLabel2.setText("Jenis");

        jLabel3.setText("Jumlah");

        jLabel4.setText("Donatur");

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel5.setText("Form Input Data Inventaris");

        tmblInput.setText("Input");
        tmblInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmblInputActionPerformed(evt);
            }
        });

        tmblKembali.setText("Kembali");
        tmblKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmblKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layarutamaLayout = new javax.swing.GroupLayout(layarutama);
        layarutama.setLayout(layarutamaLayout);
        layarutamaLayout.setHorizontalGroup(
            layarutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layarutamaLayout.createSequentialGroup()
                .addGroup(layarutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layarutamaLayout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addGroup(layarutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layarutamaLayout.createSequentialGroup()
                                .addComponent(tmblKembali)
                                .addGap(18, 18, 18)
                                .addComponent(tmblInput))
                            .addGroup(layarutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layarutamaLayout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(donatur, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layarutamaLayout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layarutamaLayout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jenis, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layarutamaLayout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(32, 32, 32)
                                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layarutamaLayout.createSequentialGroup()
                        .addGap(347, 347, 347)
                        .addComponent(jLabel5)))
                .addContainerGap(439, Short.MAX_VALUE))
        );
        layarutamaLayout.setVerticalGroup(
            layarutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layarutamaLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel5)
                .addGap(91, 91, 91)
                .addGroup(layarutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layarutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layarutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layarutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(donatur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(50, 50, 50)
                .addGroup(layarutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tmblInput)
                    .addComponent(tmblKembali))
                .addContainerGap(331, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layarutama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layarutama, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tmblKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmblKembaliActionPerformed
        // TODO add your handling code here:
        layarutama.removeAll(); 
        DataInventaris di= new DataInventaris();               
        layarutama.add(di).setVisible(true);
    }//GEN-LAST:event_tmblKembaliActionPerformed

    private void tmblInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmblInputActionPerformed
        // TODO add your handling code here:
        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/panti_asuhan","root","");
            Statement stat=conn.createStatement();
            String sql = "INSERT INTO `tabel_inventaris`(`nama`, `jenis`, `jumlah`, `donatur`) VALUES ('%s','%s','%s','%s')";
            sql = String.format(sql,nama.getText(),jenis.getText(),jumlah.getText(),donatur.getText());
            if(stat.executeUpdate(sql)==1){              
                JOptionPane.showMessageDialog(null,"ANDA BERHASIL INPUT","PEMBERITAHUAN",JOptionPane.INFORMATION_MESSAGE); 
            }
            else{
                JOptionPane.showMessageDialog(null,"MAAF ANDA TIDAK BISA INPUT","PEMBERITAHUAN",JOptionPane.INFORMATION_MESSAGE);
            }
            kosongkan_form();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            //Logger.getLogger(tambahdataanak.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_tmblInputActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField donatur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jenis;
    private javax.swing.JTextField jumlah;
    private javax.swing.JPanel layarutama;
    private javax.swing.JTextField nama;
    private javax.swing.JButton tmblInput;
    private javax.swing.JButton tmblKembali;
    // End of variables declaration//GEN-END:variables
}
